import type { Metadata } from "next";
import { Maitree, Macondo,Overpass_Mono,Oleo_Script,Courier_Prime} from "next/font/google";
import "./globals.css";

const maitree = Maitree({
  subsets: ["latin"],
  variable: "--font-maitree",
  weight: ["400", "500", "600", "700"],
});
const macondo = Macondo({
  subsets: ["latin"],
  variable: "--font-macondo",
  weight: ["400"],
});
const overpass_mono = Overpass_Mono({
  subsets: ["latin"],
  variable: "--font-overpass-mono",
  weight: ["400", "500", "600", "700"],
});
const oleo_script = Oleo_Script({
  subsets: ["latin"],
  variable: "--font-oleo-script",
  weight: ["400"],
});
const courier_prime = Courier_Prime({
  subsets: ["latin"],
  variable: "--font-courier-prime",
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "circl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${courier_prime.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
